version: '2'
services:
  jhipster_de-app:
    image: jhipster_de
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster_de-postgresql:5432/jhipster_de
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipster_de-postgresql:
    extends:
      file: postgresql.yml
      service: jhipster_de-postgresql
